name: research
channels:
  - pytorch-nightly
  - nvidia
  - default
dependencies:
  - python

  # Development
  - black
  - isort
  - flake8
  - conda-forge::pre-commit

  # pytorch
  - pytorch
  - cudatoolkit=11.3
  - torchvision
  - torchtext
  - torchaudio

  # NP Family
  - numpy
  - scipy
  - scikit-image

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  - pip
  - pip:
      - gym==0.21.0
      - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl
