alg: BehaviorCloning

optim: Adam
optim_kwargs:
  lr: 0.0005

network: ActorPolicy
network_kwargs:
  actor_class: ContinuousMLPActor
  actor_kwargs:
    output_act: ["import", "torch.nn", "Tanh"]
  hidden_layers: [512, 512]
  act: ["import", "torch.nn", "ReLU"]
  ortho_init: True

# No train env, only eval env
eval_env: null
wrapper: AntMazeGoalConditionedWrapper

dataset: GoalConditionedAntDataset
dataset_kwargs:
  d4rl_path: null
  name: null
  discount: 1.0
  reward_fn: ["import", "research.envs.ant_maze", "negative_ant_sparse"]
  batch_size: 512
  relabel_fraction: 1.0
  terminal_threshold: 0.5
  nstep: 1

processor: ConcatenateProcessor

train_kwargs: # Arguments given to Algorithm.train
  total_steps: 80000
  log_freq: 100 # How often to log values
  eval_freq: 1000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 50 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  train_dataloader_kwargs:
    num_workers: 0 # Number of dataloader workers.
    batch_size: null
    collate_fn: null
  profile_freq: 500

seed: null
