alg: GoFar
alg_kwargs:
  tau: 0.05
  target_freq: 20
  discriminator_lambda: 0.01
  hide_achieved_goal: False

optim: Adam
optim_kwargs:
  lr: 0.0005

network: GoFarNetwork
network_kwargs:
  discriminator_class: MLPDiscriminator
  discriminator_kwargs:
    act: ["import", "torch.nn", "Tanh"]
  actor_class: ContinuousMLPActor
  actor_kwargs:
    act: ["import", "torch.nn", "ReLU"]
    output_act: ["import", "torch.nn", "Tanh"]
  value_class: MLPValue
  value_kwargs:
    ensemble_size: 1
    act: ["import", "torch.nn", "ReLU"]
  hidden_layers: [512, 512]
  ortho_init: True

# No train env, only eval env
eval_env: null
wrapper: AntMazeGoalConditionedWrapper

dataset: GoalConditionedAntDataset
dataset_kwargs:
  d4rl_path: null
  name: null
  discount: 0.99
  reward_fn: ["import", "research.envs.ant_maze", "negative_ant_sparse"]
  batch_size: 512
  relabel_fraction: 1.0
  terminal_threshold: 0.5
  nstep: 1
  init_obs: True

processor: null

train_kwargs: # Arguments given to Algorithm.train
  total_steps: 80000
  log_freq: 100 # How often to log values
  eval_freq: 1000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 50 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  train_dataloader_kwargs:
    num_workers: 0 # Number of dataloader workers.
    batch_size: null
    collate_fn: null
  profile_freq: 500

seed: null
