alg: WGCSL
alg_kwargs:
  tau: 0.05
  target_freq: 20
  beta: 1
  clip_score: 10
  drw: True
  sparse_reward: True
  encoder_gradients: actor

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorCriticPolicy
network_kwargs:
  encoder_class: BridgeDataEncoder
  encoder_kwargs:
    pretrain: supervised
    num_kp: 128
    backbone: 34
    use_state_goal: True
    encode_separately: True
    stack: 2
  actor_class: ContinuousMLPActor
  actor_kwargs:
    output_act: ["import", "torch.nn", "Tanh"]
    hidden_layers: [1024, 1024]
  critic_class: ContinuousMLPCritic
  critic_kwargs:
    hidden_layers: [1024, 1024]
    ensemble_size: 1

# No train env, only eval env
eval_env: GoalConditionedWidowX200Env

dataset: BridgeDataset
dataset_kwargs:
  path: /iliad/group/datasets/bridge_data/numpy_fixed
  discount: 1.0
  batch_size: 256
  relabel_fraction: 1.0
  train: True
  capacity: 800000
  fetch_every: 32
  alloc_goal: False
  stack: 2
  stack_all: False
validation_dataset_kwargs:
  capacity: 20000
  fetch_every: 4
  train: False

processor: ComposeProcessor
processor_kwargs:
  processors: # Format is List[Tuple(Name, kwargs)]
   -
    - FlattenDict
    -
   -
    - RandomCrop
    - size: [112, 112]
      pad: 0


schedule: null # A learning rate schedule
checkpoint: null # A checkpoint to initialize the model from

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000
  log_freq: 250 # How often to log values
  eval_freq: 1000 # How often to run evals
  eval_fn: null
  loss_metric: q
  max_validation_steps: 100
  train_dataloader_kwargs:
    num_workers: 4 # Number of dataloader workers.
    batch_size: null
    collate_fn: null
  validation_dataloader_kwargs:
    num_workers: 2
  profile_freq: 250
  benchmark: True

seed: null
